FCMQT.language = {}
FCMQT.language.us = {
	-- Menu
	["lang_fcmqt_settings"] = "FCMQT Settings",
	["lang_global_settings"] = "Global Settings",
	
	["lang_language_settings"] = "Language",
	["lang_preset_settings"] = "Preset",
	["lang_overall_transparency"] = "Overall Transparency",
	["lang_overall_width"] = "Overall Width",
	["lang_position_lock"] = "Lock Background Position",
	["lang_backgroundcolor_opt"] = "Enable Background Color",
	["lang_backgroundcolor_value"] = "Background Color",

	["lang_mouse_settings"] = "Mouse Controls Settings",
	["lang_mouse_1"] = "Mouse Left Button",
	["lang_mouse_2"] = "Mouse Center Button",
	["lang_mouse_3"] = "Mouse Right Button",
	["lang_mouse_4"] = "Mouse Button 4",
	["lang_mouse_5"] = "Mouse Button 5",

	["lang_area_settings"] = "Zones Quests Settings",
	["lang_area_name"] = "Show Quests Area Name",
	["lang_area_font"] = "Quests Area Font",
	["lang_area_style"] = "Quests Area Font Style",
	["lang_area_size"] = "Quests Area Font Size",
	["lang_area_padding"] = "Quests Area Padding Size",
	["lang_area_color"] = "Quests Area Color",
	["lang_autohidequestzone_option"] = "Enable Auto Hide Zone",
	["lang_questzone_option"] = "Show Quests in Current Zone Only",
	["lang_quests_guild"] = "Show Guilds Quests",
	["lang_quests_mainstory"] = "Show Main Story Quests",
	["lang_quests_cyrodiil"] = "Show Cyrodiil Quests",

	["lang_quests_settings"] = "Quests Settings",
	["lang_quests_sort"] = "Sort Quests By...",
	["lang_quests_nb"] = "Displayed Quests",
	["lang_quests_level"] = "Show Quests Level",
	["lang_quests_optinfos"] = "Show Optional Hidden Quests Infos",
	["lang_quests_autoshare"] = "Auto Share Quests",
	["lang_quests_autountrack"] = "Auto Untrack Hidden Quests",
	["lang_icon_opt"] = "Enable Assisted Quest Icon",
	["lang_icon_texture"] = "Assisted Quest Icon Texture",
	["lang_icon_size"] = "Assisted Quest Icon Size",
	["lang_icon_color"] = "Assisted Quest Icon Color",
	["lang_quests_transparency_opt"] = "Enable Transparency for No Focused Quests",
	["lang_quests_transparency"] = "No Focused Quests Transparency",

	["lang_titles_settings"] = "Titles Settings",
	["lang_titles_font"] = "Titles Font",
	["lang_titles_style"] = "Titles Font Style",
	["lang_titles_size"] = "Titles Font Size",
	["lang_titles_padding"] = "Titles Padding Size",
	["lang_titles_default"] = "Default Titles Color",
	["lang_titles_custom"] = "Custom Titles Colors",
	["lang_titles_veasy"] = "Titles Color for Very Easy Quests",
	["lang_titles_easy"] = "Titles Color for Easy Quests",
	["lang_titles_normal"] = "Titles Color for Normal Quests",
	["lang_titles_hard"] = "Titles Color for Hard Quests",
	["lang_titles_vhard"] = "Titles Color for Very Hard Quests",

	["lang_obj_settings"] = "Objectives Settings",
	["lang_obj_font"] = "Objectives Font",
	["lang_obj_style"] = "Objectives Font Style",
	["lang_obj_size"] = "Objectives Font Size",
	["lang_obj_padding"] = "Objectives Padding Size",
	["lang_obj_color"] = "Objectives Font Color",
	["lang_obj_ccolor"] = "Completed Objectives Font Color",
	["lang_obj_optcolor"] = "Optional Objectives Font Color",
	["lang_obj_optccolor"] = "Completed Optional Objectives Font Color",

	["lang_infos_settings"] = "Infos Settings",
	["lang_infos_opt"] = "Show Infos",
	["lang_infos_font"] = "Infos Font",
	["lang_infos_style"] = "Infos Font Style",
	["lang_infos_size"] = "Infos Font Size",
	["lang_infos_color"] = "Infos Font Color",
	
	-- Menu tips
	["lang_language_settings_tip"] = "Set your language",
	["lang_preset_settings_tip"] = "Select a preset",
	["lang_overall_transparency_tip"] = "Change the global transparency",
	["lang_overall_width_tip"] = "Change the window width",
	["lang_position_lock_tip"] = "Lock/Unlock position and enable mouse actions",
	["lang_backgroundcolor_opt_tip"] = "Enable background color",
	["lang_backgroundcolor_value_tip"] = "Change the background color",
	
	["lang_mouse_1_tip"] = "Set an action for the left click",
	["lang_mouse_2_tip"] = "Set an action for the center click",
	["lang_mouse_3_tip"] = "Set an action for the right click",
	["lang_mouse_4_tip"] = "Set an action for the button 4",
	["lang_mouse_5_tip"] = "Set an action for the button 5",
	
	["lang_area_name_tip"] = "Enable the quest zone name",
	["lang_area_font_tip"] = "Set the font for the quest zone",
	["lang_area_style_tip"] = "Set the font style the quest zone",
	["lang_area_size_tip"] = "Change the font size for quest zone",
	["lang_area_padding_tip"] = "Change the left and right padding size for quest zone",
	["lang_area_color_tip"] = "Change the color for the quests zone",
	["lang_autohidequestzone_option_tip"] = "Follow the focused quest and hide others quests zones",
	["lang_questzone_option_tip"] = "Show quests in the current zone only",
	["lang_quests_guild_tip"] = "Show guilds quests",
	["lang_quests_mainstory_tip"] = "Show main story quests",
	["lang_quests_cyrodiil_tip"] = "Show Cyrodiil quests",

	["lang_quests_sort_tip"] = "Set the order for quests",
	["lang_quests_nb_tip"] = "Change the number of quest displayed",
	["lang_quests_level_tip"] = "Show quests level",
	["lang_quests_optinfos_tip"] = "Show hidden infos for optional quests",
	["lang_quests_autoshare_tip"] = "Enable the quest auto share when you are in group",
	["lang_quests_autountrack_tip"] = "Untrack on the compass all hidden quests",
	["lang_icon_opt_tip"] = "Enable the quest icon",
	["lang_icon_texture_tip"] = "Set the icon for the current assisted quest",
	["lang_icon_size_tip"] = "Change the icon size",
	["lang_icon_color_tip"] = "Change the color for the quest icon",
	["lang_quests_transparency_opt_tip"] = "Enable the transparency for other quests than the focused quest",
	["lang_quests_transparency_tip"] = "Change the transparency of no focused quests",

	["lang_titles_font_tip"] = "Set the font for the quest names",
	["lang_titles_style_tip"] = "Set the font style the quest names",
	["lang_titles_size_tip"] = "Change the font size for quest names",
	["lang_titles_padding_tip"] = "Change the left and right padding size for quest names",
	["lang_titles_default_tip"] = "Change the color of quest names",
	["lang_titles_custom_tip"] = "Enable changing color from player level",
	["lang_titles_veasy_tip"] = "Change the color of quest names < level - 4",
	["lang_titles_easy_tip"] = "Change the color of quest names <= level - 2",
	["lang_titles_normal_tip"] = "Change the color of quest names = level +- 1",
	["lang_titles_hard_tip"] = "Change the color of quest names >= level + 2",
	["lang_titles_vhard_tip"] = "Change the color of quest names > level + 4",	
	
	["lang_obj_font_tip"] = "Set the font for the quest text",
	["lang_obj_style_tip"] = "Set the font style the quest text",
	["lang_obj_size_tip"] = "Change the font size for quest text",
	["lang_obj_padding_tip"] = "Change the left and right padding size for quest text",
	["lang_obj_color_tip"] = "Change the color of quest text",
	["lang_obj_ccolor_tip"] = "Change the color of the completed objectives text",
	["lang_obj_optcolor_tip"] = "Change the color of optional quest text",
	["lang_obj_optccolor_tip"] = "Change the color of the completed optional objectives text",

	["lang_infos_opt_tip"] = "Display total of current quests",
	["lang_infos_font_tip"] = "Set the font for informations",
	["lang_infos_style_tip"] = "Set the font style for informations",
	["lang_infos_size_tip"] = "Change the font size for informations",
	["lang_infos_color_tip"] = "Change the font color for informations",
	
	-- Menu Warn
	["lang_menu_warn_1"] = "|c8B1E1E Change this option will reload the UI",
	["lang_menu_warn_2"] = "|c8B1E1E Change this option will reload the UI and overwrites your current settings",

	-- Quests Infos
	["quest_optional"] = "Optional",
	["quest_hint"] = "Hint",	
	["quest_hiddenhint"] = "Hidden Hint",
	
	["lang_tracker_type_guild"] = "Guild",
	["lang_tracker_type_mainstory"] = "Main Story",
	["lang_tracker_type_dungeon"] = "Dungeon",
	["lang_tracker_type_class"] = "Class",
	["lang_tracker_type_craft"] = "Craft",
	["lang_tracker_type_group"] = "Group",
	
	-- Mouse Interactions
	["lang_mouse_ctrl_assisted"] = "Change Assisted Quest",
	["lang_mouse_ctrl_filterzone"] = "Filter by Current Zone",
	["lang_mouse_ctrl_share"] = "Share a Quest",
	["lang_mouse_ctrl_showmap"] = "Show on Map",
	["lang_mouse_ctrl_remove"] = "Remove a Quest",
	
	-- Console
	["lang_console_autoshare"] = "You auto share a quest",
	["lang_console_share"] = "You share a quest",
	["lang_console_noshare"] = "This quest is not shareable",
	["lang_console_abandon"] = "Abandon quest",
}